### ISSUE TITLE
CSS: usage of REM and EM

### ISSUE THREAD

**Issue by sohilpandya** [FAC10/week1-jzlp#62]
What is the teams reason for using REM and EM in CSS?

You've been pretty consistent in using `rem` with the exception of a couple of places in the project where you've used `em` [here](https://github.com/FAC10/week1-jzlp/blob/master/public/assets/css/styles.css#L171) and [here](https://github.com/FAC10/week1-jzlp/blob/master/public/assets/css/styles.css#L183). If you want to use REM throughout I'd **recommend** that you have a top level default which everyone in the team is aware of. For e.g.
```css
html {
    font-size: 16px; /* for REM size declarations */
    font-family: 'Ubuntu', Helvetica, Ariel, sans-serif;
}

body {
    min-height: 100vh;
    background-color: #fafafa;
    font-size: 1rem; /* 16px */
    margin: auto;
}
```

Having this at the top level means that you are now basing the `rem` of a known size, for the above case its 16px. Finally being really picky but the media query width size should also be in `rems` so that we are using it consistently and not mixing and matching with `px`, `rem` & `em`

Great job! :smile:
